version: '3.8'

name: ccsappvp2-fleet-dev

# Deploy this stack to test the database for development
# We recommend to use MongoDB Compass for local database access
services:
  mongo:
    image: mongo:6
    restart: 'no'
    ports:
      # expose port 27031 (reserved for the FleetManagement microservice database) for local access
      - "27031:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ccsappvp2fleet
    volumes:
      - ./init-user.js:/docker-entrypoint-initdb.d/init-user.js:ro
